name: Integration Tests
on: [ push ]
jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:14
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: rhtask
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm ci
      - run: npm run db:migrate
        env:
          NODE_ENV: test
      - name: Unit tests
        run: npm test
        env:
          NODE_ENV: test
