name: Integration Tests
on: [ push ]
jobs:
  check-jsons:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install

      - name: Unit tests
        run: npm test
